const {test,expect}=require('@playwright/test');
const {createFixture,user}=require('../helpers/habit-db.cjs');

test('an outdated habit service cannot enable reward or deletion actions',async({page})=>{
 await page.route('**/*.supabase.co/**',r=>r.abort());await page.goto('/');await expect(page.locator('#auth-form')).toBeVisible();
 await page.evaluate(async()=>{
  window.habitWrites=0;
  supabase={rpc:async(_name,args)=>{if(args.p_action!=='list')habitWrites++;return {data:{avatar:{gold:50},habits:[{id:'old-service',title:'Beber agua',type:'positive',frequency:'daily',habit_timezone:'UTC',period:'2026-10-09',recorded:false,current_streak:0,best_streak:0,rewards:{xp:10,gold:5}}]}};},from:()=>({select:async()=>({data:[]})})};
  GameState.user={id:'old-server-account'};await HabitProgress.load();App.showMainApp();App.navigate('habits');
 });
 await expect(page.locator('.habit-management-notice')).toContainText('mantenimiento');
 await expect(page.getByRole('button',{name:'EN MANTENIMIENTO'})).toBeDisabled();
 await page.locator('.habit-options summary').click();
 await expect(page.getByRole('button',{name:'Eliminar hábito',exact:true})).toBeDisabled();
 await page.evaluate(async()=>{await HabitProgress.act('complete','old-service');await HabitProgress.act('archive','old-service');});
 expect(await page.evaluate(()=>habitWrites)).toBe(0);
 expect(await page.evaluate(()=>GameState.avatar.gold)).toBe(50);
});

test('water completes with one click, advances from two to three liters and retains history after reset and archive',async({page},testInfo)=>{
 test.setTimeout(60000); // The local PostgreSQL runtime also starts inside this UI test.
 const db=await createFixture();
 let day='2026-10-05';
 try {
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[user]);
  const action=async args=>(await db.query('SELECT public.habit_action_at($1,$2,$3::jsonb,$4,$5::date,$6::timestamptz) AS result',[
   args.p_action,args.p_id||null,JSON.stringify(args.p_config||{}),args.p_value??null,args.p_expected_period||null,`${day}T18:00:00Z`])).rows[0].result;
  await page.exposeFunction('habitRpc',async args=>{try{return {data:await action(args),error:null};}catch(e){return {data:null,error:{code:e.code}};}});
  await page.exposeFunction('habitHistory',async id=>({data:(await db.query('SELECT * FROM public.habit_activity WHERE user_id=$1 AND ($2::text IS NULL OR habit_id=$2) ORDER BY created_at DESC',[user,id])).rows,error:null}));
  await page.route('**/*.supabase.co/**',route=>route.abort());
  const boot=async()=>{
   await page.goto('/');await expect(page.locator('#auth-form')).toBeVisible();
   await page.evaluate(async uid=>{
    supabase={rpc:(_name,args)=>window.habitRpc(args),from:()=>{
     let id=null;const q={select(){return q;},eq(key,value){if(key==='habit_id')id=value;return q;},order(){return q;},limit(){return q;},then(resolve,reject){return window.habitHistory(id).then(resolve,reject);}};return q;
    }};
    GameState.user={id:uid};GameState.avatarId='a';GameState.avatar.lastPenaltyCheck=new Date().toISOString();
    await HabitProgress.load();App.showMainApp();App.navigate('habits');
   },user);
  };
  await boot();
  const catalog=page.locator('.catalog-card').filter({has:page.locator('#freq-select-hab_water')});
  await catalog.locator('summary').click();
  await expect(catalog.locator('[data-progress="initial"]')).toHaveValue('2');
  await expect(catalog.locator('[data-progress="required"]')).toHaveCount(0);
  await expect(catalog.locator('.habit-config-example')).toContainText('7 veces seguidas');
  await expect(catalog.locator('[data-habit-reward]')).toHaveText('+10 XP · +5 monedas');
  await expect(catalog.locator('select[data-progress="unit"]')).toHaveCount(0);
  await expect(catalog).not.toContainText('unidades');
  await expect(catalog).not.toContainText('páginas');
  await catalog.getByRole('button',{name:'+ ACTIVAR MISIÓN',exact:true}).click();
  const sleep=page.locator('[data-progress-habit]').filter({has:page.getByRole('heading',{name:/^Beber \d+ litros de agua$/})});
  await expect(sleep.getByRole('heading')).toHaveText('Beber 2 litros de agua');
  await expect(sleep).toContainText('2 litros');
  await expect(sleep).not.toContainText('America/');
  await sleep.getByRole('button',{name:'MARCAR COMPLETADO',exact:true}).click();
  await expect(page.locator('#habit-measured')).toHaveCount(0);
  await expect(sleep.getByRole('button',{name:'COMPLETADO',exact:true})).toBeDisabled();
  await expect(sleep).toContainText('Ya completaste este hábito hoy.');
  const id=await sleep.getAttribute('data-progress-habit');
  for(let d=6;d<=11;d++){day=`2026-10-${String(d).padStart(2,'0')}`;await action({p_action:'complete',p_id:id,p_value:2,p_expected_period:day});}
  await boot();
  await expect(sleep).toContainText('NIVEL 2');await expect(sleep).toContainText('3 litros');await expect(sleep).toContainText('Mejor racha: 7');
  await expect(sleep.getByRole('heading')).toHaveText('Beber 3 litros de agua');
  await page.screenshot({path:testInfo.outputPath('habit-progression.png'),fullPage:true});
  await sleep.screenshot({path:testInfo.outputPath('habit-card.png')});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await sleep.locator('.habit-options summary').click();
  page.once('dialog',async dialog=>{expect(dialog.message()).toContain('historial');await dialog.accept();});
  await sleep.getByRole('button',{name:'Reiniciar progreso'}).click();
  await expect(sleep).toContainText('NIVEL 1');await expect(sleep).toContainText('Mejor racha: 7');
  await expect(sleep.getByRole('button',{name:'COMPLETADO',exact:true})).toBeDisabled();
  await sleep.locator('.habit-options summary').click();
  page.once('dialog',dialog=>dialog.accept());
  await sleep.getByRole('button',{name:'Eliminar hábito'}).click();
  await expect(sleep).toHaveCount(0);
  await expect(page.locator('[data-progress-habit]').filter({hasText:'Legacy'})).toHaveCount(1);
  await page.getByRole('button',{name:'HISTORIAL GENERAL'}).click();
  await expect(page.getByRole('dialog')).toContainText('Beber 2 litros de agua');
  await page.getByRole('button',{name:'CERRAR',exact:true}).click();
  await boot();await expect(sleep).toHaveCount(0);
  const balance=(await db.query("SELECT gold,current_xp FROM public.avatars WHERE id='a'")).rows[0];
  await page.locator('.catalog-card').filter({has:page.locator('#freq-select-hab_water')}).getByRole('button',{name:'+ ACTIVAR MISIÓN',exact:true}).click();
  await expect(sleep).toHaveCount(1);
  await expect(sleep.getByRole('button',{name:'COMPLETADO',exact:true})).toBeDisabled();
  await sleep.locator('.habit-options summary').click();
  await expect(sleep.getByRole('button',{name:'Eliminar hábito',exact:true})).toBeDisabled();
  const retry=await page.evaluate(id=>HabitProgress.act('complete',id,{},2,'2026-10-11'),id);
  expect(retry.status).toBe('already_recorded');
  expect((await db.query("SELECT gold,current_xp FROM public.avatars WHERE id='a'")).rows[0]).toEqual(balance);
  expect((await action({p_action:'archive',p_id:id})).status).toBe('delete_cooldown');
  await expect(page.locator('.habit-management-notice')).toContainText('24 horas');
  day='2026-10-12';
  const cardio=(await action({p_action:'create',p_config:{catalog_id:'hab_cardio',frequency:'3x_week',timezone:'UTC'}})).habit_id;
  day='2026-10-13';await boot();
  const rest=page.locator(`[data-progress-habit="${cardio}"]`);
  await expect(rest.getByRole('button',{name:'DÍA DE DESCANSO'})).toBeDisabled();
  await expect(rest).toContainText('Lunes, miércoles y viernes');
  const sleeping=(await action({p_action:'create',p_config:{catalog_id:'hab_sleep',frequency:'daily',timezone:'UTC'}})).habit_id;
  await boot();
  const fixed=page.locator(`[data-progress-habit="${sleeping}"]`);
  await expect(fixed.getByRole('progressbar',{name:'Tu meta de hoy'})).toHaveAttribute('max','1');
  await expect(fixed.getByRole('progressbar')).toHaveAttribute('value','0');
  await expect(fixed).toContainText('Esta meta se mantiene igual');
  await fixed.getByRole('button',{name:'MARCAR COMPLETADO'}).click();
  await expect(fixed.getByRole('progressbar')).toHaveAttribute('value','1');
  await fixed.screenshot({path:testInfo.outputPath('sleep-fixed-card.png')});
  await fixed.locator('.habit-options summary').click();
  await fixed.getByRole('button',{name:'Activar niveles'}).click();
  await expect(page.getByRole('dialog')).toContainText('horas');
  await expect(page.getByRole('dialog').locator('select[data-progress="unit"]')).toHaveCount(0);
  await page.getByRole('dialog').getByRole('button',{name:'GUARDAR',exact:true}).click();
  await expect(fixed).toContainText('5 horas');
  await expect(fixed.getByRole('progressbar')).toHaveAttribute('max','7');
  await expect(fixed.getByRole('button',{name:'COMPLETADO',exact:true})).toBeDisabled();
  const readingCatalog=page.locator('.catalog-card').filter({has:page.locator('#freq-select-hab_read')});
  await readingCatalog.locator('summary').click();
  await readingCatalog.locator('[data-progress="initial"]').fill('10');
  await expect(readingCatalog.locator('.catalog-card-title')).toHaveText('Leer 10 páginas de un libro');
  await expect(readingCatalog.locator('.habit-config-example')).toContainText('sube a 15 páginas');
  await readingCatalog.locator('[data-progress="enabled"]').uncheck();
  await expect(readingCatalog.locator('[data-progress="initial"]')).toBeHidden();
  await expect(readingCatalog.locator('.catalog-card-title')).toHaveText('Leer 15 Páginas de un Libro');
  await expect(readingCatalog.locator('[data-habit-reward]')).toHaveText('+25 XP · +12 monedas');
  await readingCatalog.locator('[data-progress="enabled"]').check();
  await expect(readingCatalog.locator('.catalog-card-title')).toHaveText('Leer 10 páginas de un libro');
  await readingCatalog.screenshot({path:testInfo.outputPath('habit-settings.png')});
  const viewport=page.viewportSize();
  await page.setViewportSize({width:320,height:800});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await readingCatalog.screenshot({path:testInfo.outputPath('habit-settings-small.png')});
  await page.setViewportSize(viewport);
  await expect(readingCatalog.locator('[data-progress="required"]')).toHaveCount(0);
  await readingCatalog.getByRole('button',{name:'+ ACTIVAR MISIÓN',exact:true}).click();
  const reading=page.locator('[data-progress-habit]').filter({has:page.getByRole('heading',{name:'Leer 10 páginas de un libro',exact:true})});
  const readingId=await reading.getAttribute('data-progress-habit');
  for(let d=13;d<=19;d++){day=`2026-10-${d}`;await action({p_action:'complete',p_id:readingId,p_value:10,p_expected_period:day});}
  await boot();
  await expect(page.locator(`[data-progress-habit="${readingId}"]`).getByRole('heading')).toHaveText('Leer 15 páginas de un libro');
  await page.setViewportSize({width:320,height:800});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.evaluate(()=>{I18N.current='en';App.navigate('habits');});
  const englishReading=page.locator(`[data-progress-habit="${readingId}"]`);
  await expect(englishReading.getByRole('heading')).toHaveText('Read 15 pages of a book');
  await expect(englishReading.getByRole('progressbar',{name:'Progress to next level'})).toBeVisible();
  await englishReading.locator('.habit-options summary').click();
  await expect(englishReading.getByRole('button',{name:'History',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 } finally {await db.close();}
});
